### ISSUE TITLE
Build error!

### ISSUE THREAD

**Issue by Jonanthandx** [rabume/cs2-dma-radar#13] opened 2023-11-16 23:13 UTC
I got this error when I tried to build the project.
![Screenshot 2023-11-16 173437](https://github.com/rabume/cs2-dma-radar/assets/69990788/b67fe4c0-4903-4478-a443-2d93a0ac1d13)

And this error when run the jar file downloaded from release
![Screenshot 2023-11-16 173437](https://github.com/rabume/cs2-dma-radar/assets/69990788/e272e638-01af-4d26-ac1e-cecc55ed5261)

**Comment by xCorteX** [comment] 2023-11-18 09:26
remove line 12 from makefile file
	@if [ ! -d "client/node_modules" ]; then \
	
	
 release download ist outdate

**Comment by rabume** [comment] 2023-11-18 15:14
When building the project, make sure that make is working as intended and install the node dependencies first. 
Commenting out the conditional check will just result in another error while building. 

To use make on Windows, I recommend using [cygwin](https://cygwin.com/) to install it.

Thanks to @xCorteX which updated the offsets, I was able to create a new release which 
should work for you.

**Comment by rabume** [comment] 2023-11-18 15:28
> remove line 12 from makefile file @if [ ! -d "client/node_modules" ]; then \
> 
> release download ist outdate

It could be a solution for the people which run the make command in a non bash environment because that syntax only works in a bash shell. I use the cygwin terminal
on Windows, which works with this syntax.

**Comment by kirysnik** [comment] 2023-11-19 17:48
still the same error 
![Screenshot_6](https://github.com/rabume/cs2-dma-radar/assets/150271956/0f5576a2-0a9c-48e8-9656-310813d7d861)
and got this after make build error in line 16 but what exactly went wrong idk 
![Screenshot_7](https://github.com/rabume/cs2-dma-radar/assets/150271956/8a5e8c11-e0ad-4644-adf8-cdd5c984a6ae)

**Comment by kirysnik** [comment] 2023-11-19 18:11
Same thing goes on in cygwin terminal but without any error in make build...

**Comment by xCorteX** [comment] 2023-11-19 20:14
> still the same error ![Screenshot_6](https://user-images.githubusercontent.com/150271956/284079418-0f5576a2-0a9c-48e8-9656-310813d7d861.png) and got this after make build error in line 16 but what exactly went wrong idk ![Screenshot_7](https://user-images.githubusercontent.com/150271956/284079477-8a5e8c11-e0ad-4644-adf8-cdd5c984a6ae.png)



You can copy the file that was created with the error from the app/target/ folder and paste it into the release folder

**Comment by kirysnik** [comment] 2023-11-20 10:03
![Screenshot_8](https://github.com/rabume/cs2-dma-radar/assets/150271956/0c1a05de-e544-4117-a22d-5b903533eff1)
The makefile error after copying the file from target folder disappeared, but still same issue. Also now my release folder look like this... 
![Screenshot_9](https://github.com/rabume/cs2-dma-radar/assets/150271956/9ccd3730-eeab-4f7c-ad51-1f479f2b79f4)

**Comment by xCorteX** [comment] 2023-11-20 10:18
It looks like your DMA card is not recognized. VMM cannot initialize with your card

which dma card do you have?

**Comment by kirysnik** [comment] 2023-11-20 10:21
I have squirrel and already changed firmware 2 times and 1 try was on wifi from ekknod.

**Comment by kirysnik** [comment] 2023-11-20 10:29
So I see the problem like this. My card is reading memory before starting the cheat. After I run java -jar cs2dma.... my card is stopped. what is it ...
![Screenshot_10](https://github.com/rabume/cs2-dma-radar/assets/150271956/10e7aac0-a19a-4402-8fe0-19ad77932604)
![Screenshot_11](https://github.com/rabume/cs2-dma-radar/assets/150271956/68e6f3ca-83b4-4586-8691-c185610d43aa)
![Screenshot_12](https://github.com/rabume/cs2-dma-radar/assets/150271956/56b8e6fd-fd31-4765-b362-8f7795c9fb0a)

**Comment by xCorteX** [comment] 2023-11-20 10:41
Unfortunately, I don't know anything about the DMA card. You might have to create a mmap.txt for it.

But then you also have to insert it into the script so that the mmap.txt is read

"GameDataManager.java"
`private static String[] argvMemProcFS = { "", "-device", "FPGA", -memmap", "mmap.txt" };`

**Comment by kirysnik** [comment] 2023-11-20 11:32
Maybe @rabume will know what's the reason why my card is behaving like that. I'm not good at programming, totally newbie at it so. I do not know how to make mmap.txt unluckily

**Comment by rabume** [comment] 2023-11-20 18:52
Hey y'all :wave: 
It looks like you have a main board / AMD CPU which needs manual mapping.
Did you ever use your card with any other cheat? Did it work?

I can build in an auto mmap dumper to generate the mmap on the fly, but when
you have an AMD cpu this will not work either.

Let me know what your system specs are.

**Comment by kirysnik** [comment] 2023-11-20 20:09
So I have AMD Ryzen 5 3600 and Gigabyte A320m-h. I did not use yet, it's my first try to :D

**Comment by rabume** [comment] 2023-11-20 21:05
There is. You would have to generate your mmap.txt manually on your target computer.
I know that some paid cheat providers offer such tools, but I don't know about any free,
open-source ones.

If you know somebody who has access to such a provider, you could ask them to share
it with you. If you need some names of paid cheat providers, reach out to me via email.

**Comment by xCorteX** [comment] 2023-11-20 21:51
I have one tool
I could contact you via Discord then I could help you create an mmap

Discord : killing1337

**Comment by kirysnik** [comment] 2023-11-20 22:32
added

**Comment by xCorteX** [comment] 2023-11-20 23:04
i added you and send the mmap generator 
and found this 

Change the following BIOS settings on the Gaming-PC

On Intel disable VT-d
On AMD disable IOMMU

**Comment by rabume** [comment] 2023-11-23 19:39
I will add the option to use a mmap.txt later. Closing this issue now
Thanks, @xCorteX, for helping out.

**Closed by rabume** 2023-11-23 19:39 UTC
Labels: question

**Comment by ffFliman** [comment] 2024-04-03 16:38
[makefile:15: build] Error 1

**Comment by ffFliman** [comment] 2024-04-03 16:38
mvn is not an internal or external command

**Comment by rabume** [comment] 2024-04-03 16:42
This is a closed issue. Make sure you have mvn installed and exposed in your PATH.

**Comment by ffFliman** [comment] 2024-04-03 17:31
![FireShot Capture 001 - Upload files · rabume_cs2-dma-radar - github com](https://github.com/rabume/cs2-dma-radar/assets/31286534/55ff6ae4-982e-4b8c-ab98-a34f4386e5af)
Everything started, but enemies and allies are not visible

**Comment by ffFliman** [comment] 2024-04-03 17:35
![222222222222222222](https://github.com/rabume/cs2-dma-radar/assets/31286534/9d6ba54b-10eb-41dc-8470-a04982a75715)
![111111111111111111111111](https://github.com/rabume/cs2-dma-radar/assets/31286534/065b6b1a-98e7-450c-92b8-b668cc6d3cb1)
my release folder look like this...

**Comment by itsRiver** [comment] 2024-05-24 19:09
im sadly facing the same as the op :(.

It was working before, suddenly its gives me the same error. Ive reinstalled mvn, jdk & make countless of times. Any ideas? 

The release itself works
